### ISSUE TITLE
Response {"message": "Forbidden", ...}

### ISSUE THREAD

**Issue by Adnan-Shahid** [aws-samples/simple-websockets-chat-app#24]
I directly deployed this project through aws, and deployed it, I can connect using wscat -c url, but when I try to send any message I get a response (with actual strings for connectionid and request id):
{"message": "Forbidden", "connectionId":"some_string", "requestId":"some_string"}

Is there a step that needs to be applied outside of the deployment that is not documented? (I did definitely deploy the api and stage it)

**Comment by createbuildship** [comment]
same here, can't figure out. Did u find an answer  @Adnan-Shahid

**Comment by Adnan-Shahid** [comment]
I haven't been able to find the cause yet either unfortunately

**Comment by createbuildship** [comment]
Hey Adnan, give me a ping on chris@frontr.co.uk and lets get connected so I can share you what i did to make it work. I just don't have time to write it up

**Comment by dgomesbr** [comment]
hey @frontr-uk @Adnan-Shahid, I'm in paternity leave, if you can, share the details here and we'll incorporate on the repo. Thank you

**Comment by Adnan-Shahid** [comment]
@frontr-uk It appears more than just us have this issue, it would be great if you could share how you solved it here for everyone

**Comment by markotitel** [comment]
Also had the same issue. Searching through closed issues helped me.
The same issue is opened and the answer is at the bottom https://github.com/aws-samples/simple-websockets-chat-app/issues/23

SendMessage lambda needs to be built before deployment. Use `npm install` and then the procedure is the same.

Actually there are two errors that may occur, at least those two I've noticed so far.
First is `{"message": "Internal server error", "connectionId":"Zo4APfrwIAMCK8w=", "requestId":"Zo4BOG05oAMF9dA="}`.
When you look to CloudWatch logs `/aws/lambda/simple-websocket-chat-app-OnDisconnectFunction-*` you'll notice issue with AWS-SDK and `require('aws-sdk/clients/apigatewaymanagementapi')` this issue is similar https://github.com/aws/aws-sdk-js/issues/2520
This error is solved by `npm install` in sendmessage directory. Then `sam package` and `sam deploy`.

The other error is basically not sending proper payload. Check your request json data.
This is proper one `{"message":"sendmessage", "data":"hello world"}`
Maybe you have something like `"message":"sendMessage", "data":"hello world"}`
Or `{ "action": "sendmessage", “data”: "Hello, I am using WebSocket APIs in API Gateway.” }`.

**Comment by markotitel** [comment]
You can checkout this PR https://github.com/aws-samples/simple-websockets-chat-app/pull/25
This should work out of the box.

**Comment by dgomesbr** [comment]
fixed by #25

**Comment by Adnan-Shahid** [comment]
This doesn't seem to be fixed when deploying directly from AWS's Serverless Application Respository. I get the same error

**Comment by dgomesbr** [comment]
@jt0 could sync it again or grant me privileges to do so?

**Comment by aushakov95** [comment]
@dgomesbr @markotitel 
Deploying via the AWS CLI produces the same error for me.
`{"message": "Forbidden", "connectionId":"connectionId_here", "requestId":"requestid_here"}`

**Comment by markotitel** [comment]
@aushakov95 Have you deployed from serverless repo or from github?

**Comment by carnivaloftrees** [comment]
> 
> 
> @aushakov95 Have you deployed from serverless repo or from github?

I have personally tried both and I have the "Forbidden" error each time :(

**Comment by aushakov95** [comment]
@markotitel @carnivaloftrees 
Yes I have tried both.
But I figured out why it was not working for me!
I was sending this via wscat
`{"action": "sendmessage"...}`
per instructions on the aws guide for this repo.

So what fixed it for me was typing in
`{"message": "sendmessage"...}` instead.

**Comment by carnivaloftrees** [comment]
@aushakov95 
Really? Because I just tried with what you've just said and I still get the same error:
**{"message": "sendmessage","data": "test"}
{"message": "Forbidden", ...}**

Am I still missing something?

Thanks for the suggestion though, it gives me a lead at least.

**Comment by carnivaloftrees** [comment]
Is my wscat connection ok?

**wscat -c wss://(ID).execute-api.(REGION).amazonaws.com/Prod**

**Comment by aushakov95** [comment]
@carnivaloftrees

Your connection url is right. 

This is a bit of a long shot, but go to the sendmessage route inside API Gateway and click “add integration response”. Try again

**Comment by carnivaloftrees** [comment]
> 
> 
> @carnivaloftrees
> 
> Your connection url is right.
> 
> This is a bit of a long shot, but go to the sendmessage route inside API Gateway and click “add integration response”. Try again

Still giving me forbidden! What do you pass through as data? Just anything? Thanks for help by the way, I appreciate it, I really want to be able to use the websocket.

**Comment by ngPati** [comment]
Same issue here :(

**Comment by acahinton** [comment]
Anyone still having this issue deploying via the AWS SAR - the code does not currently reflect the master branch here so you can make the following changes to resolve:

In the "sendMessage" lambda; change the runtime to node 10 and remove the following line from the sendmessage/app.js
 - require('aws-sdk/clients/apigatewaymanagementapi');

![image](https://user-images.githubusercontent.com/1495139/59194268-68b0c200-8b80-11e9-96aa-c3bd2dba19e8.png)

Deploying via the command line using AWS SAM works fine from a download of the current master branch code.

**Comment by hsmr29** [comment]
@acahinton 

I did what you said, but I still see the same error as the others. **Forbidden**

**Comment by ngPati** [comment]
@acahinton Node 10.x fixed the issue for me :)

**Comment by acahinton** [comment]
@Hugosimon29 -  I take it you are formatting the message as follows:

`{"message":"sendmessage", "data":"hello world"}`

If so, it might be worth deleting your cloudformation stack for this sample, then re-adding via AWS SAR and making the above two small changes to see if that helps?

I've now set up deployments from Bitbucket calling the SAM CLI to deploy and it's working fine as a base that I can then develop from. Is that an option (or similar) given that the AWS SAR latest build is broken?

**Comment by dgomesbr** [comment]
I'm back from leave, took ownership of the SAR, will review and sync repo/publish app next week, sorry about the whole problem and lack of attention folks.

**Comment by XJIOP** [comment]
```
> {"message":"sendmessage", "data":"hello world"}
< {"message": "Forbidden", "connectionId":"bkxyKepxLPECH6g=", "requestId":"bkxzcGywrPEFstw="}
```

problem in "sendmessage" should be "sendMessage"

**Comment by iDevo** [comment]
Hey guys! I deployed the app using AWS directly and faced the same issue. In a conclusion to all mentioned possible solutions I tested 3 different code changes:

1. Original version with Node 8
2. Applied changes from @acahinton with Node 10 and commented line 7 in `sendmessage`
3. Applied the changes from the GitHub commit #25 from [May 13 ](https://github.com/aws-samples/simple-websockets-chat-app/commit/5972a6a2492d3d0b684634870161ee477859080f#diff-98f51b42168563316bc515497b571574)manually to the websocket-chat-app

Each time testing all of the following parameter using `wscat`:
```
{“action”:“sendMessage”, “data”:“hello world”}
{“action”:“sendmessage”, “data”:“hello world”}
{“message”:“sendMessage”, “data”:“hello world”}
{“message”:“sendmessage”, “data”:“hello world”}
```

Unfortunately nothing helped so far and I am still getting the error message in the terminal:
`{"message": "Forbidden", "connectionId":"<ID>=", "requestId":"<ID>"}`

I also tried to debug the app myself but the `sendmessage` function seems to not be triggered at any time, while the connecting and disconnecting works like a charm. I could not find any problems in the API Gateway but in my opinion the issue might be located in there there.

Cheers!

**Comment by autoCAT6** [comment]
Guys if you're still having that "message: Forbidden" error on "sendmessage" route, it's probably because you didn't capitalize that "M". 
I changed my lambda function runtime to Node.js 10.x and deleted that require statement in app.js, then sent my json payload as "{"message":"sendMessage","data":"hello"}". Everything worked perfectly.

**Comment by hardingmatt** [comment]
Thanks- changing `{"action":"sendmessage", "data":"hello world"}` to `{"message":"sendMessage", "data":"hello world"}` was all I needed.

@dgomesbr Would it be possible to edit the blog post to reflect this change?  Thank you!

https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/

**Comment by DaisukeNagata** [comment]
https://twitter.com/i/status/1146440093046996993

Double quotes are automatically changed on Mac Notepad.
so I could not chat.
And I did. Thank you very much.

**Comment by pilgrim2go** [comment]
I deployed using serverless console and got the same issue.
Fix 1
```
changing {"action":"sendmessage", "data":"hello world"} to {"message":"sendMessage", "data":"hello world"}
```
Another issue 
```
{"message": "Internal server error", "connectionId":"Zo4APfrwIAMCK8w=", "requestId":"xxx="}
```
Fix 2
I have to run 
` cd /simple-websockets-chat-app/sendmessage`
`npm install`
`zip -r package.zip .` 
and then update sendMessage Lambda to solve the issue

**Comment by Gharaibeh** [comment]
I tried to send after connect : 
 {"message":"sendMessage","data":"hello"}
But I got this error as reply: 
< {"message": "Internal server error", "connectionId":"-----", "requestId":"-----"}

**Comment by appindus-kanderson** [comment]
There were a number of helpful comments above. After troubleshooting for a bit I was able to successfully connect and send a message with the following configuration:

 - Deploy the application as is from the SAR.
 - After application is deployed update the SendMessageFunction lambda function to use Node.js runtime version 10.x.
 - In the same SendMessageFunction lambda function, remove the ApiGatewayManagementApi from the AWS name space (comment out line 7 of the function code. https://github.com/aws-samples/simple-websockets-chat-app/issues/24#issuecomment-500393045)
 - Save the lambda.
 - Test connection with `wscat -c wss://{ID}.execute-api.{REGION}.amazonaws.com/{STAGE}` (this can be found in the dashboard section of the API Gateway service. ([image link](https://d2908q01vomqb2.cloudfront.net/1b6453892473a467d07372d45eb05abc2031647a/2018/12/18/websockets-api-dashboard.png))
 For example `wscat -c wss://123456.execute-api.us-east-1.amazonaws.com/Prod`
 - Test payload/response with the  following payload `{"message":"sendMessage", "data":"hello world"}`. Make note of the `message` key and its' `sendMessage` value. These are different than what's documented.
 - The above `wscat` connection was verified in a browser environment with the following: 
```
const SOCKET_URL = `wss://123456.execute-api.us-east-1.amazonaws.com/Prod`
const connection = new WebSocket(SOCKET_URL)
connection.onopen = function () {
  const payload = {"message":"sendMessage", "data":"hello world"}
  connection.send(JSON.stringify(payload))
}
// Log errors
connection.onerror = function (error) {
  console.log('WebSocket Error ' + error);
};

// Log messages from the server
connection.onmessage = function (e) {
  console.log('Server: ' + e.data);
};
```
Hope this helps.

**Comment by fimbox** [comment]
I set up the pipeline with a simple custom lambda function without the SAR deployment:
`
exports.handler = async (event, context) => 
{
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};
`
I constantly got the "message": "forbidden" answer with wscat.

I finally solved the issue by using **$request.body.message** instead of $request.body.action in the Route Selection Expression.

Of course we also need to send the matching route key like "sendMessage" instead of "onmessage"

![grafik](https://user-images.githubusercontent.com/28051000/68552195-92fafa00-0414-11ea-8575-2e0b84de6d0e.png)

**Comment by thatguyfig** [comment]
Hi all,

Today I deployed this template from the SAR, and had to do the following to get this to work correctly.

1.  Take note of the Route setup - i.e. check the names of the following:
![image](https://user-images.githubusercontent.com/22985628/69234307-bd705400-0b86-11ea-8411-d779a81e15f2.png)

2. This means you will have to modify your input JSON within **wscat** to accomodate these differences. i.e:
`{"message": "sendMessage", "data": "message to send to other clients"}`

3. Changing only this, your error will move from _Forbidden_ to _Internal Server Error_. To overcome this, do as mentioned by @acahinton 
https://github.com/aws-samples/simple-websockets-chat-app/issues/24#issuecomment-500393045
3a. Comment out line for aws-sdk require
3b. Update Lambda Function to use Node.Js 10

3. Redeploy your API to the target stage and you should now be able to send and receive data from different clients without errors.

Let me know if that doesn't work because it definitely did for me.

Thanks,
Tom

**Comment by Ronald-Saunfe** [comment]
Thanks a lot it worked but i had to create a new Websocket API since i could not change the route from '$request.body.action' to '.message'

**Comment by iqdavidh** [comment]
Hi, I had the same issue,  This changes allows to get it works

https://github.com/iqdavidh/simple-websockets-chat-app

I changed the api gateway acording to another example.

**Comment by SahajRana** [comment]
Using `Deploy Api` again from `Actions`, after adding a new route, did the trick for me.

**Comment by jagadish432** [comment]
1) For the error "Forbidden" :
-> When you send the request {"action": "<custom_route>", "message": "some text "}, make sure that the first key ("action" here ) is based on the value of "route selection expression" you gave in API gateway i.e., for MY above example request to work, the route selection expression should be "$request.body.action".

2) For the error "Internal server error":
-> a) Give proper required "cloudwatch logs access" to the role which you applied for the AWS Lambda functions.
b) Check the logs so that your lambda function should n't fail i.e., dependencies should be given correctly, exception handling and provide some print statements for better debugging.
c) API gateway will return 504(if lambda takes more time than 30 seconds which means gateway will time out) and 502(if lambda doesn't give a proper response which gateway can understand)

**Note:** lambda should provide a response in the form of { "statusCode": 200, "<message/result>": "some result response text"} in case of python (  "callback(None, response) in case of NoeJS, I'm not sure about other languages )

Let me know if this solves for you, reply back if the error still occurs.

**Comment by soumilshah1995** [comment]
> * require('aws-sdk/clients/apigatewaymanagementapi');  



> Hi all,
> 
> Today I deployed this template from the SAR, and had to do the following to get this to work correctly.
> 
> 1. Take note of the Route setup - i.e. check the names of the following:
>    ![image](https://user-images.githubusercontent.com/22985628/69234307-bd705400-0b86-11ea-8411-d779a81e15f2.png)
> 2. This means you will have to modify your input JSON within **wscat** to accomodate these differences. i.e:
>    `{"message": "sendMessage", "data": "message to send to other clients"}`
> 3. Changing only this, your error will move from _Forbidden_ to _Internal Server Error_. To overcome this, do as mentioned by @acahinton
>    [#24 (comment)](https://github.com/aws-samples/simple-websockets-chat-app/issues/24#issuecomment-500393045)
>    3a. Comment out line for aws-sdk require
>    3b. Update Lambda Function to use Node.Js 10
> 4. Redeploy your API to the target stage and you should now be able to send and receive data from different clients without errors.
> 
> Let me know if that doesn't work because it definitely did for me.
> 
> Thanks,
> Tom

I am using Python Lambda and getting internal Server Error can anyone Help i followed all steps showed in Github Comments

**Comment by soumilshah1995** [comment]
> Anyone still having this issue deploying via the AWS SAR - the code does not currently reflect the master branch here so you can make the following changes to resolve:
> 
> In the "sendMessage" lambda; change the runtime to node 10 and remove the following line from the sendmessage/app.js
> 
> * require('aws-sdk/clients/apigatewaymanagementapi');
> 
> ![image](https://user-images.githubusercontent.com/1495139/59194268-68b0c200-8b80-11e9-96aa-c3bd2dba19e8.png)
> 
> Deploying via the command line using AWS SAM works fine from a download of the current master branch code.
Whats the solution for people who are using python Lambda Function

**Comment by oscarnevarezleal** [comment]
Ha! For some reason the last version of this repo I use created `sendmessage` (mind the lowercase) so my payload needed to look like this `{"message": "sendmessage", "data": "message to send to other clients"}`

Works fine.

**Comment by dgomesbr** [comment]
The SAR is out-of-date, I'm on leave, as soon as I'm back I'll clean the issues, publish a new version of the SAR and update the blog post.

Thanks for the patience.

**Comment by jonathanmv** [comment]
> Ha! For some reason the last version of this repo I use created `sendmessage` (mind the lowercase) so my payload needed to look like this `{"message": "sendMessage", "data": "message to send to other clients"}`
> 
> Works fine.

I'm using all-lowercase `sendmessage` and it works for me

**Comment by dgomesbr** [comment]
Hello folks, I've updated the SAR (https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:729047367331:applications~simple-websockets-chat-app) to 1.0.3, which mirrors the latest changes in this repo.

I've also reverted the RouteSelectionExpression to $request.body.action to match the Blog post.

so now, the blog post examples should work with:

``` {"action": "sendmessage", "data": "message to send to other clients"} ```

Thanks for the continued patience on this one.

**Comment by NASlR** [comment]
Thanks for fixing. Could you update the readme on the repo? It's still got the old RouteSelectionExpression (which then led me to finding this issue)

**Comment by dgomesbr** [comment]
Done

**Comment by BossLevel** [comment]
To anyone who may still be having issues with this, specifically, submitting a message via a browser-based socket, rather than via wscat, the following may help. I had deployed a tweaked version of this repo and had no problem sending messages via wscat. However I had also knocked up a webpage to test sending via the browser, and whilst I could connect, any messages sent failed with the same Forbidden message. I knew there wasn't a problem with the data being sent as I could cut and paste it into wscat and it would send so it must be something else. However I did notice that in wscat, if the JSON object was malformed e.g. no double quotes, it would fail with the same error.

`{ "action": "sendmessage", "data": "message" }` - good
`{ action: "sendmessage", data: "message" }` - bad

In the browser JS, I was defining the message as follows:

`var scktMsg = {"action":"sendmessage", "data":message};` (message being a string variable)

however I noticed when logging in the console, the object was shown as `{ action: "sendmessage", data: "message" }` and this was failing.

I solved the problem by stringifying the object and this was then accepted by the API:

`ws.send(JSON.stringify(scktMsg));`

Hope this helps as it drove me up the wall for a day and a half! ;-(

**Comment by fsobh** [comment]
> To anyone who may still be having issues with this, specifically, submitting a message via a browser-based socket, rather than via wscat, the following may help. I had deployed a tweaked version of this repo and had no problem sending messages via wscat. However I had also knocked up a webpage to test sending via the browser, and whilst I could connect, any messages sent failed with the same Forbidden message. I knew there wasn't a problem with the data being sent as I could cut and paste it into wscat and it would send so it must be something else. However I did notice that in wscat, if the JSON object was malformed e.g. no double quotes, it would fail with the same error.
> 
> `{ "action": "sendmessage", "data": "message" }` - good
> `{ action: "sendmessage", data: "message" }` - bad
> 
> In the browser JS, I was defining the message as follows:
> 
> `var scktMsg = {"action":"sendmessage", "data":message};` (message being a string variable)
> 
> however I noticed when logging in the console, the object was shown as `{ action: "sendmessage", data: "message" }` and this was failing.
> 
> I solved the problem by stringifying the object and this was then accepted by the API:
> 
> `ws.send(JSON.stringify(scktMsg));`
> 
> Hope this helps as it drove me up the wall for a day and a half! ;-(

JSON.stringify fixed it for me!

**Comment by tayyabgilani** [comment]
@dgomesbr This is what I am doing to initiate a was connect chat from the lambda function

` const connection = new WebSocket(url);

             var test = { "message": "sendMessage", "data": "hello" };
             connection.onopen = () => {
                 connection.send(JSON.stringify(test));
                 console.log("connection open?????");
             };
             connection.onerror = error => {
                 console.log(`WebSocket error: ${error}`);
             };
             connection.onmessage = e => {
                 console.log("On message come here?????");
                 console.log("EEEE", JSON.stringify(e));
                 console.log(e.data);
             };`
but still having the same error 
`{
    "message": "Forbidden",
    "connectionId": "xxxxxxxx",
    "requestId": "xxxxxx"
}`

**Comment by S1rFrancis** [comment]
In the `connection.onopen` are you subscribing to the topic. For instance when connecting to connect participant chat:

```
this.ws.onopen = (e) => {
      this.ws.send(
        JSON.stringify({
          topic: 'aws/subscribe',
          content: { topics: ['aws/chat'] },
        }),
      );.......
```

**Comment by bpottier** [comment]
We’re attempting to send a message over a websocket connection for AWS connect are have tried everything and always get “Forbidden”. Anyone get past this issue?

**Comment by tuanardouin** [comment]
@bpottier 
I created a sample a few months ago using CDK :
https://github.com/tuanardouin/WebSocket-CDK

You can try to compare the different role et permissions set in this stack to yours to pinpoint the problem maybe?

**Comment by baigzeeshan** [comment]
For Timeout and Internal Server Errors...check Lambda function Timeout and increase it to at least 1 minute, the API tries to delete the stale connections from Dynamo DB which takes more than the default Lambda timeout 3 seconds. In my case, I was testing with 300 connections.

**Comment by charlescol** [comment]
For "Forbidden" error, my solution was to remove the root with an uppercase and to create another one with only lowercases. It works for me.

**Comment by VeereshPratap** [comment]
@bpottier Hey, I am doing the same thing-trying to connect to Amazon Connect Chat via websocket-years later and still encountering this issue. Did you ever manage to solve it? I would really appreciate your telling me the approach if you solved it. Thank you.
