### ISSUE TITLE
Does not work when changing Function on API GatewayV2 Integration

### ISSUE THREAD

**Issue by andrew-templeton** [aws-samples/simple-websockets-chat-app#26]
When you change the ARN of a function or an integration, this template does not make a new deployment. 

Try changing the logical name of the Function for one of the handlers, along with the references to it (to use the new logical name of the function), and repackage and deploy the SAM package. 

No new deployment will be triggered, because the Deployment resource, even with the explicit DependsOn, will not make a new deployment. The old function (with the older logical name in the template) will be deleted, and the API will continue to try to access the old function's ARN. 

There does not seem to be any way to force an in-place replacement safely of the Deployment resource. I have needed to change the logical name of the Deployment resource to be something like: 

Deployment<sha1 hash of the directory being packaged> to work around this. It caused a pretty serious outage on our end when using this SAM pattern without that. Beware to folks using this template if you're doing anything that causes a full-replacement on any of the Lambda resources or API Gateway Integrations.

**Comment by acahinton** [comment]
I had maybe a similar issue where adding a new route after initial deployment was not being picked up - this was caused because the API Gateway was not being automatically redeployed to the Prod stage so the new route was not recognised. Manually deploying to Prod then made the route available.

For my issue I'm going to investigate forcing the template to redeploy the API to the Prod stage.

Apologies if this isn't the same fix for the above... but thought I'd mention it as a possibility...

**Comment by dgomesbr** [comment]
@andrew-templeton  have you tried to publish the newly deployed SAM app?

**Comment by dgomesbr** [comment]
Closing as stale.
