### ISSUE TITLE
Integrate Socket API into existing CloudFront Solution

### ISSUE THREAD

**Issue by ghost** [aws-samples/simple-websockets-chat-app#5]
Hi,

thanks for the sample, which helped us a lot to understand how to use **WebSockets** with **Amazon API Gateway**. We were able to create a new Socket API for our solution based on the samples. We wanted to integrate it created via **Amazon CloudFront** into our existing solution (according to the AWS Documentation WebSockets should work on CloudFront: https://goo.gl/4AMRPb).

Currently we do have a **CloudFront** distribution (incl. CNAME with e.g. `mydomain,com`) with multiple origins

* an S3 Origin where we do have the frontend  (`frontendOrigin`)
* a custom origin for the API  (`apiOrigin`)
* an additional S3 Origin, where we also store frontend pictures (`picturesOrigin`)

For these origins we created several Cache Behaviours:

* The Default **(*)** behaviour is pointing to `frontendOrigin`
* A Behaviour with Path Pattern **/api/*** which is pointing to `apiOrigin`
* A Behaviour with Path Pattern **/pictures/*** which is pointing to `picturesOrigin`

Now we wanted to integrate our new Socket API created via API Gateway to CloudFront and created a new Origin called socketOrigin with a Behaviour with Pattern **/api/socket** which is pointing to socketOrigin (with the correct precedence).

After redeploying the distribution we were not able to open a connection to the socket, because of a ** HTTP 403** Status code. I found a way to get more details by using a curl:

```bash
curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: <cloudfrontid>.cloudfront.net" \
     --header "Origin: https://<cloudfrontid>.cloudfront.net/api/socket" \
     --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
     --header "Sec-WebSocket-Version: 13" \
     https://<cloudfrontid>.cloudfront.net/api/socket
```

We got the following response back by **CloudFront**:

```
HTTP/1.1 403 Forbidden
Content-Type: application/json; charset=UTF-8
Content-Length: 75
Connection: close
Date: Thu, 10 Jan 2019 09:57:07 GMT
X-Cache: Error from cloudfront
Via: 1.1 blahblahblah.cloudfront.net (CloudFront)
X-Amz-Cf-Id: YxowUpxLm6t3VEV1Foue36kmdrOilhVlxqHN0S59dy-7cca681LiHw==
```

We thought, that it might have something to do with the path pattern, as we don't specify any wildcard, so we switched the path pattern to **/api/socket/*** , but this didn't help. We checked the **Viewer Protocol Policy** (HTTP & HTTPS) and **Origin Protocol Policy** (Match Viewer), but this also didn't help to solve the 403.

So, here is the question, if **Amazon API Gateway** & **Amazon CloudFront** is working with WebSocket APIs and if yes, how it must be configured to get to work. Can you provide any samples? If it is not working yet, we would like to open a feature request to support the above mentioned configuration.

Kind Regards,
Marcell

**Comment by dgomesbr** [comment]
**_auto:_** add to my `to-do` for week `5`.

**Comment by dgomesbr** [comment]
**_auto:_** bump from week `5` to  week `10`

**Comment by dgomesbr** [comment]
@jt0 do you have any spare time to take a look onto this one? I've bumped twice and I'll probably be locked until week 10/2019.

**Comment by bjorg** [comment]
@kirnberger were ever able to get this to work? Or is it basically not working?

**Comment by m-radzikowski** [comment]
I believe problem here is path mapping between CloudFront and API Gateway.

Let's say you have WebSocket API Gateway with id `mce8m6z8s8` and stage `v1`. The WebSocket URL is then: `wss://mce8m6z8s8.execute-api.eu-central-1.amazonaws.com/v1`

When you want to connect to the WS, you must connect to exactly this URL. If you try to connect to, let's say, `wss://mce8m6z8s8.execute-api.eu-central-1.amazonaws.com/v1/whatever`, you will get 403 forbidden error.

Now you attach this API Gateway to the CloudFormation though the behavior with path pattern `/api/socket`. When you call `xxxx.cloudfront.net/api/socket` CF sends a request to the API Gateway URL: `wss://mce8m6z8s8.execute-api.eu-central-1.amazonaws.com/v1/api/socket` instead of root path.

CloudFront does not cut the path from the request when sending it to the origin. It is not possible to configure either.

See possible path mappings here: https://advancedweb.hu/how-to-use-api-gateway-with-cloudfront/#origin-request-url - at the end always full path is passed to the origin.

The only workaround I see to configure WS on path is to set API Gateway stage name, for example "socket", and then configure path pattern for it. So you can have it working on url `xxxx.cloudfront.net/socket`

**Comment by dgomesbr** [comment]
As @m-radzikowski mentioned, this isn't the default behavior. I'll pass this as a feature request, but closing for now.

**Comment by bjorg** [comment]
@dgomesbr Please do. I already mentioned it to Katrina Bakas. This is really annoying, because it requires us to use the WebSocket stagename in our front-end application code, which is not ideal.

**Comment by faustomilletari** [comment]
Dear all,

I am writing in this thread because i really don't know where to look anymore. The issue experienced by the user ghost is very similar to mine, even though i didn't use any of the code of this repo.

I am in dire need of having an unsecured websocket connection which i can't realize with a straight ApiGateway on AWS, as we all know.

My idea was to use CloudFront to allow HTTP/HTTPs access to the websocket endpoint.

I have therefore set up a CloudFront distribution. I am fairly sure that everything is okay there. I chose not to cache anything, and to accept everything from the viewer (headers, etc).

My api gateway endpoint for the websocket is somethng like wss://xxxxxxx.execute-api.us-east-1.amazonaws.com/stage

What is did was to indicate as origin in the cloud front distribution `wss://xxxxxxx.execute-api.us-east-1.amazonaws.com` and path `/stage` and as behavior i have indicated both HTTP or HTTPs connection plus the caching behavior and header forwarding i have just mentioned. 

It should all be pretty standard. 

when i try to connect via `ws://yyyyy.cloudfront.net` or even `wss://yyyyy.cloudfront.net` I receive error 403.

A portion of my response header report is here:

```
x-amz-apigw-id: TA01EHd5IAMF84w=
X-Amz-Cf-Id: f_6Ka5sqZsyiXXIRqstsBXEKmJLDPCiE24nVBrwnoR9wweOPzVGRGQ==
X-Amz-Cf-Pop: PMO50
X-Cache: Error from cloudfront
```
Of course i have also tried to indicate as origin name `wss://xxxxxxx.execute-api.us-east-1.amazonaws.com` and path `/` in this case my request would be made to `ws://yyyyy.cloudfront.net/stage` but the result would be identical. 

I really don't know what else to try. I have activated logs for cloudfront, towards a logs S3 bucket, but there is nothing there apart for a generic "error" message. I have also activate cloudwatch logs for the API Gateway and whenever I make a request directly to  `wss://xxxxxxx.execute-api.us-east-1.amazonaws.com/stage` i can see that it is successful (as expected) but NONE of the requests that were made via cloudfront distribution at either `ws://yyyyy.cloudfront.net/stage` or `ws://yyyyy.cloudfront.net` are reported at all. At this point i start thinking cloudfront doesn't even talk with the api gateway, but whenever i try to contact the host with a simple `wget http://yyyyy.cloudfront.net` i receive an Upgrade error which means, somwhere, somehow something that relates to the websocket is being actually triggered. 

Please let me know if you know a way, any way, to get rid of SSL in the api gateway. I don't need to use cloud front. i just cannot use SSL on my IoT device because of memory constraints.

**Comment by bjorg** [comment]
@faustomilletari It took me a while to get CloudFront to work with WebSocket. You can see a sample of the integration here which uses LambdaSharp notation, but it's close enough to CloudFormation YAML to follow: https://github.com/LambdaSharp/Chat/blob/main/Module.yml#L164

However, I will tell you that there is no way to connect over HTTP/WS. You have to use HTTPS/WSS. CloudFront will redirect any HTTP connection to HTTPS. It does not serve a HTTP connection. So if SSL is not supported by your device, you are out of luck with API Gateway. Instead, you will need to run something like an EC2 instance to act as a WS relay or server.

**Comment by faustomilletari** [comment]
Thank you Bjorg. Your insight is helpful. I was indeed hoping to just do the same I have already done with a rest endpoint I had. In that case cloud front helped getting http without ssl layer. That said... I will look at the file you pointed and I will post here if I get it to work with either https or even http (which at this point I’m a bit discouraged about) 

At this point I am almost about running EC2 instances with fastapi websocket which would probably be even better. 

The thing is... lambda allows to scale in a way thy even eks struggles to do.

Thank you very much for your help. I appreciate it

**Comment by nikolazius** [comment]
Hey there, 
I spent perhaps more than a day, but found the catch. You need to configure the Origin Request Policy properly. Here is an example for WebSockets : https://nickzamosenchuk.medium.com/configure-amazon-cloudfront-cdn-for-websocket-connection-43c44b3f877c

Cheers!

**Comment by dgomesbr** [comment]
Would make send to create a new repo or add this example/functionality to the readme?

**Comment by vonhan** [comment]
> Hey there, 
> I spent perhaps more than a day, but found the catch. You need to configure the Origin Request Policy properly. Here is an example for WebSockets : https://nickzamosenchuk.medium.com/configure-amazon-cloudfront-cdn-for-websocket-connection-43c44b3f877c
> 
> Cheers!

Dear @nzamosenchuk 
thank you so much for your guide! Unfortunately despite this guide my API gateway websocket continues to be unreacheable through CloudFront.

If I follow your guide using a new distribution with the default CF SSL certificate works, instead in my case where I'm using a custom SSL certificate provided by me doesn't work. 

Thanks!

**Comment by httpiga** [comment]
> Hey there,
> I spent perhaps more than a day, but found the catch. You need to configure the Origin Request Policy properly. Here is an example for WebSockets : https://nickzamosenchuk.medium.com/configure-amazon-cloudfront-cdn-for-websocket-connection-43c44b3f877c
> 
> Cheers!

Just for sharing some general knowledge: this solution works because API Gateway does not want an Host header different from the one assigned to each endpoint (eg: xxxxxx.execute-api.eu-central-1.amazonaws.com ). Whitelisting websocket headers prevents the Host header (ie: your ClouFront distribution URL) to be forwarded, so CloudFront will use the API Gateway endpoint as value for the Host header.

**Comment by vonhan** [comment]
@httpiga I confirm that solution works! The errors was due to a miss configuration on my side. 😅
